@startuml OOP
!theme crt-green
class Buscaminas{
tablero: Tablero
}
class Tablero{
casilla: int 
}
class Minas{
victoria: bool
boom()
}
class Jugador{
perder()
ganar()
jugar()
}
Minas -|> Tablero: have 5 >
Buscaminas <|-- Tablero
Jugador <|- Buscaminas: only 1 player >
@enduml