@startuml OOP
!theme crt-green
class Buscaminas{
interfaz: Tablero
}
class Tablero{
casilla: int 
}
class Minas{
perder()
boom()
}
class Jugador{
victoria: bool
jugar()
}
Minas -|> Tablero: have 5 >
Buscaminas <|-- Tablero
Jugador <|- Buscaminas: only 1 player >
@enduml